CREATE DATABASE annuaire;
use annuaire;

CREATE TABLE coordonnees(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL
);